const express = require('express');
const bodyparser = require('body-parser');
const path = require('path');
const fs = require('fs');


var app = express();

//set view engine
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));

//bodyparser middleware
app.use(bodyparser.json());
app.use(bodyparser.urlencoded({
  extended: false
}));

//set static path
app.use(express.static(path.join(__dirname, 'public')));

app.get('/add', function(req, res) {
  res.render('add', {});
});

app.get('/draw', function(req, res) {
  res.render('draw', {});
});

app.get('/show', function(req, res) {
  var images = {};
  fs.readFile('./images.json', function(err, data) {
    if (err) {
      console.log(err);
    }
    images = JSON.parse(data);
    res.render('show', {
      imagesList: images
    });
  });
});

app.get('/', function(req, res) {
  res.render('index', {});
});

app.post('/add', function(req, res) {
  fs.readFile('./images.json', 'utf8', function readFileCallback(err, data) {
    if (err) {
      console.log(err);
    } else {
      obj = JSON.parse(data); //now it an object
      var count = Object.keys(obj).length + 1;
      obj[count] = req.body.imageurl;
      json = JSON.stringify(obj); //convert it back to json
      fs.writeFile('./images.json', json, 'utf8', function(err) {
        if (err) {
          console.log(err);
        }
      }); // write it back
    }
  });
  res.render('thanks', {});
});

app.post('/draw', function(req, res) {
  // string generated by canvas.toDataURL()
  var img = req.body.data;
  var rawImg = img.replace(/^data:image\/png;base64,/, "");

  /*  fs.readdir('./public/pictures', function(err, filenames) {
      if (err) {
        console.log(err);
      }
      imgurl = filenames.length + 1;
    });*/

  fs.readFile('./images.json', 'utf8', function readFileCallback(err, data) {
    if (err) {
      console.log(err);
    } else {
      obj = JSON.parse(data); //now it an object
      var count = Object.keys(obj).length + 1;
      obj[count] = "pictures/image_" + count + ".png";
      json = JSON.stringify(obj); //convert it back to json
      fs.writeFile('./images.json', json, 'utf8', function(err) {
        if (err) {
          console.log(err);
        }
      }); // write it back
      fs.writeFile('./public/pictures/image_' + count + '.png', rawImg, 'base64', function(err) {
        if (err) {
          console.log(err);
        }
      });
    }
  });
  res.render('thanks', {});
});

app.listen(8080, function() {
  console.log('server started on port 8080');
});